sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt clean coverage test && sbt coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_install:
- pip install --user codecov
after_success:
- codecov
- "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt 'set version := version.value + \".\" + System.getenv(\"TRAVIS_BUILD_NUMBER\")' ; };"
env:
  global:
  - secure: QxmkMzK3rlY5olbqACmsWXUNDZKFx/ymX3NKukOHcZ2qNPv91jOZrvbn9Udyi4Ly3sDWWLTZWvKdJbWcMm4q+YlqHHYoNNgpi16VfYiy2pStGnBw6J9iKJ4SVmgIIiz4GohpObjxL50hyqnFvJyubBwROpnbSxZYE4yBQ//WYJwi4gvA3Hw6fRgLyIS6+9SnELuhx8/zTMudB9K8349kerIQkC8Ka/2r/zc0thBD+2h3FoW+U4YyaGpNRIG7q2QLLNumlEQhLstuMkqyX4wOqkZ9n6uL07yrlLKAXdVbBS0B1KMT+oETsMonya7cLBz17E2ONxywWDA3woXfZv1CMv3gxtW4Ut46mcP0fBqJlXuYa1GS3KX+O26G+fczo8f6iBqrNcepndXvgfA8qBbtdzt7xLO0Sy3MJ5OdzE3Tk7073ig2TfU5Lp5oSB6ZCn76JxwXO1kwfaEv/724bLH82NwrfP5FPPOjjuf+iBTA1DK5Ctg9I7VVQP0Q40OFL6/R4Dd3SHTpjvpLHXZxY8viu503ReibcIWplyjnbfZr9Rgo5gqzvEV8go6N20WNnZmaIFlQ1nQrbrAoDOtIIqSxyfFDwqQDKcVV/TyvR4s4NJzAdMrd6NzQlSJ7QYopOtvEi7XX7MUYGkn4oIJEWOM1CfZHWNO5HL0kvuiUZC/MG9Y=
  - secure: eA564pTlgrfmhUIuSI/2dHNew5WtGMZNnNRCQtJLpzmIqIg09yCCL5zI3n3fXVu1DBlALS/vlI38gBwaMNfIHbT5QL5H0dNnV7weSpE0O1Z3OPSFOf+wE4kuvM4x0LaUrhqAEegothAUGx8/+q2VLaC5/tpxfmy+AtbnDLYg3pYEFIZSsNoq8GmB457SDchhl7HaLxd8FNBSBH7H+srzHR1gkfcLc7ktI3yy3XgHIzwP78Dv+Y6SZSJaLuzllOjK1KTH9i0wtEJ202GyWnBhmiV0q4XovZexsRCE1sLY4j2+F+DcIitJ5fafCWD5HOGl/Ef5UHSaA0QIYJJ0aSgaJ+0P/KRnR3izRzNGK5ROU4onrCFusTZzg1JiHvv0Negyc1vqGRiPSiyHPd5sPoNkruNaguwb1K6B26L19x5+qkA9gsh3pvND9lauwAEFFwvAOiyeaXJaoWJKhmvI9r3MEyhg65LEmkmvNQ+2kaWO7as7kXCgxL7LDrTQEAEp8kv8dRByxT0lEVR7Mp1dcp/RU626dYgfKW6y/u4HKA3Bv7iDIJF0fRZicbZNZmwdykcMBgK1IMqSDalU47yrON+fVqP1YngUSgrR+x4FO0q1U9RMNGiUVSV+ZcegD4YdO3IpLX6xjmZpPCB8WpAPBNyB6agBRkjhtphe9Qc2Udm6Gio=
